version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bradboard-backend
    ports:
      - "8080:8000"
    environment:
      - ENVIRONMENT=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - bradboard-network
    depends_on:
      - caddy

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2-alpine
    container_name: bradboard-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - bradboard-network

volumes:
  caddy_data:
  caddy_config:

networks:
  bradboard-network:
    driver: bridge
